### ISSUE TITLE
Cannot Download the dataset and pretrained network in mainland,China

### ISSUE THREAD

**Issue by ywcmaike** [yifeishi/PlaneMatch#1]
Hello, yifeishi(施逸飞). I'm interested in your work and want to try it. I'm the student from Zhejiang University,China. And in mainland, I cannot download the dataset and pretrained network easily. Can you send the dataset and pretrained network package to me or BaiduDisk? 
My email is 2755289083@qq.com.Thanks!

由于防火墙的原因，最近的VPN网速较渣，无法正常下载数据集和预先训练网络。能否发一份到我邮箱2755289083@qq.com. 或者是提供百度云盘的地址。谢谢。

**Comment by yifeishi** [comment]
Hi, thanks for your interest in our work. I have been uploading the data to BaiduDisk but it was very slow. Will let you know when the link is available :)

**Comment by ywcmaike** [comment]
Thanks!  Can I contact you with wechat or QQ?   I want to know more about your work.  
My wechat is 13032893650, My QQ is 2755289083

**Comment by adrienkaiser** [comment]
Hi @yifeishi, first, thanks for sharing your code and uploading your dataset.
The download links at pan.baidu.com do not seem to work outside China (in particular I am interested in training_triplets/training_triplets.zip), as it always asks me to download external Windows software.
Would it be possible to consider uploading the zip files to something like Google Drive, Dropbox.. ?
Thanks in advance !

**Comment by yifeishi** [comment]
Hi @adrienkaiser , sorry for the late response. We have recently uploaded the data to Dropbox. The links are: https://www.dropbox.com/sh/rm4lc2pa9kgosze/AAAmOuU1ExNLLGwqP1GOHhAKa?dl=0 and https://www.dropbox.com/sh/5duo5v30nmz40eq/AAC78qvsGteTKm_cUEw5A1t-a?dl=0.  Please let me know if you have any other questions :)

**Comment by adrienkaiser** [comment]
Awesome thank you !!

**Comment by jukindle** [comment]
@yifeishi TUM cluster shows 404 error (URL you provided in README.md), just saying :)
